inherit_gem:
    rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'lib/generators/**/*'
    - 'test/tmp/**/*'

Style/MethodCallWithArgsParentheses:
  Exclude:
    - '**/Gemfile'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'

